### ISSUE TITLE
WolvenKit cannot use asset browser

### ISSUE THREAD

**Issue by jake4832** [WolvenKit/WolvenKit-7#20]
**Describe the bug**
When trying to use the asset browser, I get the following error message:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at WolvenKit.frmAssetBrowser..ctor(List`1 managers) in C:\w3.modding\GIT_FUZZO_WolvenKit-7\WolvenKit\Forms\frmAssetBrowser.cs:line 57
   at WolvenKit.frmMain.OpenAssetBrowser(Boolean loadmods, String browseToPath) in C:\w3.modding\GIT_FUZZO_WolvenKit-7\WolvenKit\Forms\MVVM\frmMain.cs:line 1027
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**To Reproduce**
1. Open Wolvenkit
2. Click on "Asset browser"

**Expected behavior**
I should be able to access this, I'm sure this is some kind of issue with the next gen update

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: WolvenKit v7.0.5

**Comment by bishan178** [comment]
me too

**Comment by toffi3** [comment]
Same Issue Here

**Comment by nikich340** [comment]
> Same Issue Here

Use 7.1.0 build, it's fixed.

**Comment by jake4832** [comment]
Works now, thank you!
